<?php


namespace Modules\Frontend\Entities;


class NewsCategory extends \Modules\Backend\Entities\NewsCategory
{

    public function getRouteKeyName()
    {
        return 'slug'; // TODO: Change the autogenerated stub
    }
}
